import matplotlib.pyplot as plt
import numpy as np

def plot(name, data):
    """
    Used for plotting trajectories generated by VRNN
    """
    x = data[:, 0]
    y = data[:, 1]

    plt.figure()
    plt.xlim(5, 11)
    plt.ylim(5, 11)
    ax = plt.axes()
    ax.plot(x, y)

    plt.savefig(name + ".png")

def plot_point_trajectories(padded_trajectories, num_to_plot):
    """
    Used for plotting actual trajectories
    """
    for i in range(num_to_plot):
        traj = padded_trajectories[i] # shape thres, 6
        x = traj[:, 0]
        y = traj[:, 1]
        
        plt.figure()

        plt.xlim(5, 11)
        plt.ylim(5, 11)
        ax = plt.axes()
        ax.plot(x, y)

        plt.savefig("actplots/{}".format(str(i)))